name: Build and Deploy to Yandex cloud

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_G }}
        username: oauth
        password: ${{ secrets.CR_YANDEX_TOKEN_G }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./PartyPartUsers/PartyPartUsers
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-part-users:latest
        file: Dockerfile
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    # Push the Docker image to Google Container Registry
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_G }}
        username: ${{ secrets.HOST_USERNAME_G }}
        key: ${{ secrets.SSH_KEY_G }}
        script: |
          sudo docker stop party-part-users || true
          sudo docker rm party-part-users || true
          sudo docker pull ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-part-users:latest
          sudo docker run -p 8081:80 --name party-part-users -d ${{ secrets.DOCKER_REGISTRY_G }}/${{secrets.DOCKER_REPO_G}}/party-part-users:latest
